# Endpoint: Qlever
PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX schema: <http://schema.org/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?lexeme ?item ?lemma ?desc ?cat ?genus (wd:Q25167 as ?lang) WHERE {

  {
  # Search for lexemes in Bokmål
  ?lexeme wikibase:lemma ?lemma.
  ?lexeme  dct:language wd:Q25167.
  # Search for potentially matching items with descriptions
  ?item rdfs:label ?lemma.
  ?item schema:description ?desc.
  FILTER(LANG(?desc) = LANG(?lemma)).
  # get lexical category and genus
  ?lexeme wikibase:lexicalCategory ?cat.
  OPTIONAL { ?lexeme wdt:P5185 ?genus. } .
  }

  # Remove matches that are already connected
  FILTER NOT EXISTS {
    ?lexeme ontolex:sense ?sense.
    ?sense wdt:P5137 ?item.
  }.
  # Remove homographs since these are to error prone
  FILTER NOT EXISTS { ?lexeme wdt:P5402 ?homograph }.
  FILTER NOT EXISTS { ?lexeme wdt:P11577 ?_ }.

  # Filter properties
  FILTER NOT EXISTS { ?item a wikibase:Property}.

  # Remove various common false positives
  FILTER NOT EXISTS {
    VALUES ?not {
     wd:Q5         # human
     wd:Q395       # math
     wd:Q7187      # gene
     wd:Q7366      # song
     wd:Q7397      # software
     wd:Q8134      # economics
     wd:Q8502      # mountain
     wd:Q11424     # movie
     wd:Q11446     # ships
     wd:Q23786     # eye color
     wd:Q40056     # software
     wd:Q43229     # organization of any kind
     wd:Q101352    # family name
     wd:Q134556    # single (music)
     wd:Q147276    # names of any kind
     wd:Q170173    # yacht
     wd:Q191067    # article
     wd:Q202866    # animation movie
     wd:Q208569    # album
     wd:Q215380    # bands
     wd:Q226730    # silent movie
     wd:Q355304    # watercourse
     wd:Q482994    # album
     wd:Q494452    # heraldry
     wd:Q786820    # automobile manuf.
     wd:Q819989    # lunar crater
     wd:Q1145276   # fictional country (star trek)
     wd:Q1229071   # motif
     wd:Q1348589   # lunar crater
     wd:Q1391494   # technical terminology
     wd:Q1475691   # mars crater
     wd:Q1505023   # interpellation
     wd:Q1725664   # terminology of any kind
     wd:Q1897960   # trotting horse
     wd:Q2235308   # types of ships
     wd:Q3305213   # painting
     wd:Q3331189   # version, edition, or translation
     wd:Q3404720   # tincture
     wd:Q3491429   # military terms
     wd:Q3658341   # literary character
     wd:Q3744866   # common charge (heraldic)
     wd:Q3744880   # nature figure (heraldry)
     wd:Q4167410   # disambiguation page
     wd:Q4167836   # wikimedia cat
     wd:Q5185279   # poem
     wd:Q5398426   # tv series
     wd:Q6881511   # enterprise
     wd:Q7725634   # literary work
     wd:Q10429085  # report
     wd:Q11060274  # print
     wd:Q11668273  # shogi pieces
     wd:Q13406463  # wikimedia list article
     wd:Q13417114  # noble family
     wd:Q15056993  # aircraft family
     wd:Q15632617  # fictional person
     wd:Q15642541  # human settlement definitions
     wd:Q15831596  # class of fictional entities e.g. star wars sandcrawler
     wd:Q17155032  # type of software
     wd:Q17537576  # any creative work incl. music, video, text, etc.
     wd:Q17638537  # routine - fix computer terminology
     wd:Q18218093  # other type of art
     wd:Q19798642  # WD value
     wd:Q19798644  # wikibase model terms
     wd:Q19798645  # wikibase datatype
     wd:Q20202269  # music terms
     wd:Q21191270  # tv series episode
     wd:Q22808320  # disambig name type
     wd:Q29168811  # animated film
     wd:Q29654788  # unicode character
     wd:Q56876983  # symbol (heraldic)
     wd:Q57814795  # domesticated animal
     wd:Q58408484  # Wikimedia list of persons by surname
     wd:Q66050470  # conjugation table
     wd:Q99045339  # written question
     wd:Q99281788  # star trek location
     wd:Q105543609 # musical work
    }.
    ?item wdt:P31 ?not
  }

  # Remove various common false positives via P279 (subclass of)
  FILTER NOT EXISTS {
    VALUES ?not {
      wd:Q3918         # university
      wd:Q14745        # furniture
      wd:Q15284        # municipality
      wd:Q55043        # gymnasium
      wd:Q192249       # saddle
      wd:Q494452       # blazonry
      wd:Q783794       # company
      wd:Q13220204     # second-level administrative country subdivision
      wd:Q15911314     # association
    }.
    ?item wdt:P279 ?not.
  }
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q11446 }.     # ship
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q35872 }.     # boat
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q452237 }.    # motion
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q494452 }.    # blazonry
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q1406161 }.   # artistic theme
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q4167410 }.   # disambiguation pages
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q7302866 }.   # audio track (basshunter song)
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q14897293 }.  # fictional entity
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q17537576 }.  # creative work
  FILTER NOT EXISTS { ?item wdt:P31/wdt:P279* wd:Q23010327 }.  # fictional objects

  # filter on properties:
  FILTER NOT EXISTS {
    VALUES ?not2 {
      wdt:P131     # geographic items
      wdt:P136     # genre (music, etc)
      wdt:P195     # collection (of art)
      wdt:P688     # gene stuff
      wdt:P1482    # stack exchange
      wdt:P8514    # brazilian import that has a lot of false positives
      }
    ?item ?not2 ?_
  }.

  FILTER NOT EXISTS { ?item wdt:P361 wd:Q18336 }.              # part of heraldry

  # filter on aspect of:
  FILTER NOT EXISTS {
    VALUES ?not3 {
      wd:Q18336  # heraldry
      wd:Q494452 # blazonry
      }
      ?item wdt:P1269 ?not3
  }.

  # filter on part of:
  FILTER NOT EXISTS {
    VALUES ?not4 {
      wd:Q18336  # heraldry
      wd:Q494452 # blazonry
      }
      ?item wdt:P361 ?not4
  }.
}
