name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run query
      run: curl -f --data-urlencode "query=$(cat $GITHUB_WORKSPACE/queries/default.sparql)" "https://query.wikidata.org/sparql?format=json"
